# Generated by Django 4.1.4 on 2023-01-06 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Role',
            fields=[
                ('emp_type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_type1', models.CharField(choices=[('Service_Provider', 'Service_Provider'), ('Officer', 'Officer')], default='User', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Service_Provider', 'Service_Provider'), ('Officer', 'Officer')], max_length=20)),
                ('employee_email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('employee_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('serviceprovider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('No_of_employees', models.CharField(blank=True, choices=[('0-10', '0-10'), ('10-50', '10-50'), ('50-250', '50-250'), ('250-500', '250-500'), ('500-1000', '500-1000')], max_length=100, null=True)),
                ('founding_year', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Logo', models.ImageField(default='media/Company/defaultimage.jpg', upload_to='Company')),
                ('video_links', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_service_provider', models.BooleanField(default=False)),
                ('LinkedIn', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('reviews', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('mach_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserAccount.employee_role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Services',
            fields=[
                ('Service_Id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Service_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
