# Generated by Django 4.1.4 on 2023-01-02 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text1', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text2', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text3', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text4', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text5', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_text6', models.BooleanField(blank=True, default=False, null=True)),
                ('choice_text7', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Question_Answer',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, default='Anonymous_User', max_length=200)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('answer1', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('show', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Question.question')),
            ],
        ),
    ]
