# Generated by Django 4.1.4 on 2023-01-02 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Question_Answer',
            new_name='User_Question_Answers',
        ),
    ]
