# Generated by Django 4.1.4 on 2023-01-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_rename_user_question_answer_user_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_question_answers',
            old_name='question',
            new_name='question_id',
        ),
    ]
