# Generated by Django 4.1.4 on 2023-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_rename_question_user_question_answers_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_question_answers',
            old_name='question_id',
            new_name='question',
        ),
    ]
